### ISSUE TITLE
Missing File "hebicam-1.2-SNAPSHOT-all-x86_64.jar"

### ISSUE THREAD

**Issue by sl13** [HebiRobotics/HebiCam#3]
Hello,
I try to use your code to get the data of a mjpeg stream but I get a warning that the file "hebicam-1.2-SNAPSHOT-all-x86_64.jar" is missing and the variable "us" or class "us.hebi.matlab.streaming.DeviceLocation" is undefined (see the attached picture). I am using Windows 10 and Matlab R2015a. The path of the unzipped folder was added in the working path of Matlab. I hope you can fix the problem or help me if I make a mistake on my side. Thanks!

![error_matlab](https://user-images.githubusercontent.com/26485213/29216278-75973ade-7eae-11e7-856d-09d60e05ab38.png)

**Comment by ennerf** [comment]
You are running from source code instead of a release. Please follow the "Installation" or the "Installation from Source Code" instructions in the [README](https://github.com/HebiRobotics/HebiCam/blob/master/README.md).

Releases can be downloaded [here](https://github.com/HebiRobotics/HebiCam/releases)
